name: GitHub Build Task
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v2
      - run: g++ collapse_nodes.cpp -o collapse_nodes
      - run: ./collapse_nodes